version: '3.8'
services:
  slidev:
    image: tangramor/slidev:latest
    container_name: slidev
    user: node
    ports:
      - "3030:3030"
    environment:
      - NPM_MIRROR=https://registry.npmmirror.com
    volumes:
      - .:/slidev
    stdin_open: true
    tty: true
    restart: "no"
